document.getElementById('filmeForm').addEventListener('submit', function(event) {
    event.preventDefault(); 

    const tipoFilme = document.getElementById('tipoFilme').value;

    const filmes = {
        comedia_romantica: [
            'Simplesmente Acontece',
            'Como Eu Era Antes de Você',
            'Casa Comigo?',
            'O Amor Não Tira Férias',
            'Questão de Tempo',
            'Enquanto Você Dormia',
            'A Proposta',
            'Se Beber, Não Case!',
            'De Repente é Amor',
            'Um Amor de Tesouro',
            'Letra e Música',
            'Missão Madrinha de Casamento',
            'Recém-Casados',
            'A Verdade Nua e Crua',
            'Esposa de Mentirinha',
            'Apenas Amigos',
            'Amor a Toda Prova',
            'Um Namorado Para Minha Mulher',
            'Loucamente Apaixonados',
            'Como Se Fosse a Primeira Vez',
            'O Melhor Amigo da Noiva',
            '10 Coisas que Eu Odeio em Você',
            'O Diário de Bridget Jones',
            'Sorte no Amor',
            'Amor e Outras Drogas',
            'Amor à Segunda Vista',
            'Doce Novembro',
            'Sr. & Sra. Smith',
            'O Lado Bom da Vida',
            'Quatro Amigas e um Casamento',
            'A Teoria de Tudo',
            'Um Grande Garoto',
            'Juntos e Misturados',
            'Ele Não Está Tão a Fim de Você',
            'Sim, Senhor!',
            'Letra e Música'
        ],
        drama: [
            'A Culpa é das Estrelas',
            'Um Amor para Recordar',
            'Titanic',
            'Diário de uma Paixão',
            'Cidade dos Anjos',
            'Forrest Gump',
            'O Curioso Caso de Benjamin Button',
            'A Lista de Schindler',
            'Uma Linda Mulher',
            'O Poderoso Chefão',
            'Crepúsculo dos Deuses',
            'O Jogo da Imitação',
            'O Menino do Pijama Listrado',
            'O Óleo de Lorenzo',
            'O Resgate do Soldado Ryan',
            'O Menino de Ouro',
            'O Show de Truman',
            'O Náufrago',
            'A Vida é Bela',
            'Marley & Eu',
            'O Menino que Descobriu o Vento',
            'O Menino do Pijama Listrado',
            'O Preço da Coragem',
            'O Quarto de Jack',
            'A Onda',
            'À Espera de um Milagre',
            'Dumbo',
            'Menina de Ouro',
            'Um Sonho de Liberdade',
            'Gladiador',
            'A Origem',
            'O Silêncio dos Inocentes',
            'Pulp Fiction',
            'O Lobo de Wall Street',
            'Clube da Luta',
            'O Show de Truman',
            'Intocáveis'
        ],
        acao: [
            'Velozes e Furiosos',
            'Missão Impossível',
            'Pantera Negra',
            'Homem de Ferro',
            'John Wick',
            'Matrix',
            'Vingadores: Ultimato',
            'Esquadrão Suicida',
            'O Senhor dos Anéis: A Sociedade do Anel',
            'Batman: O Cavaleiro das Trevas',
            'Harry Potter e a Pedra Filosofal',
            'Guardiões da Galáxia',
            'Deadpool',
            'Aquaman',
            'O Senhor dos Anéis: O Retorno do Rei',
            'O Senhor dos Anéis: As Duas Torres',
            'Piratas do Caribe: A Maldição do Pérola Negra',
            'Piratas do Caribe: O Baú da Morte',
            'Piratas do Caribe: No Fim do Mundo',
            'Capitão América: O Primeiro Vingador',
            'Capitão América: O Soldado Invernal',
            'Capitão América: Guerra Civil',
            'Homem-Formiga',
            'Homem-Formiga e a Vespa',
            'Thor',
            'Thor: O Mundo Sombrio',
            'Thor: Ragnarok',
            'Os Vingadores',
            'Vingadores: Era de Ultron',
            'Capitã Marvel',
            'Homem de Ferro',
            'Homem de Ferro 2',
            'Homem de Ferro 3',
            'Homem-Aranha: De Volta ao Lar',
            'Homem-Aranha: Longe de Casa',
            'Homem-Aranha: No Aranhaverso',
            'Homem-Aranha'
        ],
        suspense: [
            'O Sexto Sentido',
            'Psicose',
            'Janela Indiscreta',
            'O Iluminado',
            'Seven: Os Sete Crimes Capitais',
            'A Origem',
            'A Lista de Schindler',
            'A Identidade Bourne',
            'Fargo',
            'Onde os Fracos Não Têm Vez',
            'Pacto Sinistro',
            'O Bebê de Rosemary',
            'Os Outros',
            'A Garota no Trem',
            'A Janela Secreta',
            'A Cela',
            'Amnésia',
            'Clube da Luta',
            'Deixa Ela Entrar',
            'Instinto Secreto',
            'O Homem Duplicado',
            'O Mistério das Duas Irmãs',
            'O Segredo dos Seus Olhos',
            'Os Suspeitos',
            'O Silêncio dos Inocentes',
            'Rear Window',
            'Se7en',
            'Silencio dos Inocentes',
            'The Prestige: O Grande Truque',
            'A Paixão de Cristo',
            'O Chamado',
            'Encontros e Desencontros',
            'A Malvada',
            'Cisne Negro',
            'Donnie Darko'
        ],
        terror: [
            'O Exorcista',
            'O Iluminado',
            'A Hora do Pesadelo',
            'O Chamado',
            'Invocação do Mal',
            'Atividade Paranormal',
            'Jogos Mortais',
            'A Casa do Espanto',
            'A Bruxa',
            'Sexta-Feira 13',
            'Halloween',
            'A Noite dos Mortos-Vivos',
            'A Casa das Almas Perdidas',
            'Coraline e o Mundo Secreto',
            'Pânico',
            'Arraste-me para o Inferno',
            'It: A Coisa',
            'O Babadook',
            'Poltergeist',
            'A Orfã',
            'A Centopeia Humana',
            'A Última Casa da Rua',
            'Aterrorizados',
            'Atividade Paranormal',
            'Carrie, a Estranha',
            'Contágio',
            'Evocando Espíritos',
            'Jogos Mortais',
            'Mama',
            'Nós',
            'O Exorcismo de Emily Rose',
            'O Ritual',
            'Ouija: Origem do Mal',
            'Ouija: O Jogo dos Espíritos',
            'Poltergeist - O Fenômeno',
            'Premonição',
            'Sobrenatural'
        ],
        ficcao_cientifica: [
            'Interestelar',
            'De Volta para o Futuro',
            'Matrix',
            'Blade Runner',
            'A Chegada',
            'E.T. - O Extraterrestre',
            'Exterminador do Futuro',
            'Eu, Robô',
            'Guerra dos Mundos',
            'Star Trek',
            'Avatar',
            'Planeta dos Macacos: A Origem',
            '2001: Uma Odisseia no Espaço',
            'Guia do Mochileiro das Galáxias',
            'O Quinto Elemento',
            'Contato',
            'Jurassic Park',
            'Os Vingadores',
            'Vingadores: Ultimato',
            'Homem-Aranha no Aranhaverso',
            'Blade Runner 2049',
            'Interestelar',
            'Os Incríveis',
            'A Origem',
            'Wall-E',
            'Star Wars: Episódio IV - Uma Nova Esperança',
            'Star Wars: Episódio V - O Império Contra-Ataca',
            'Star Wars: Episódio VI - O Retorno de Jedi',
            'Star Wars: Episódio I - A Ameaça Fantasma',
            'Star Wars: Episódio II - O Ataque dos Clones',
            'Star Wars: Episódio III - A Vingança dos Sith',
            'Star Wars: Episódio VII - O Despertar da Força',
            'Star Wars: Episódio VIII - Os Últimos Jedi',
            'Star Wars: Episódio IX - A Ascensão Skywalker',
            'O Dia Depois de Amanhã',
            'O Dia em que a Terra Parou'
        ],
        animacao: [
            'Toy Story',
            'Shrek',
            'Frozen',
            'Procurando Nemo',
            'A Era do Gelo',
            'Os Incríveis',
            'A Bela e a Fera',
            'Monstros S.A.',
            'Divertida Mente',
            'Zootopia',
            'O Rei Leão',
            'Aladdin',
            'Moana',
            'Cinderela',
            'A Pequena Sereia',
            'Ratatouille',
            'Meu Malvado Favorito',
            'Como Treinar o seu Dragão',
            'Carros',
            'Kung Fu Panda',
            'Up: Altas Aventuras',
            'Wall-E',
            'Valente',
            'A Princesa e o Sapo',
            'Os Croods',
            'O Bicho Vai Pegar',
            'Tarzan',
            'Hércules',
            'Madagascar',
            'A Fuga das Galinhas',
            'O Fantástico Sr. Raposo',
            'Rio',
            'A Lenda de Despereaux',
            'Planeta 51',
            'Astro Boy',
            'A Casa Monstro'
        ],
        documentario: [
            'Supersize Me: A Dieta do Palhaço',
            'Fahrenheit 9/11',
            'A Queda de um Gigante',
            'Nanook of the North',
            'The Thin Blue Line',
            'Crumb',
            'Roger & Me',
            'Koyaanisqatsi',
            'Hearts and Minds',
            'Woodstock',
            'Inside Job',
            'Waltz with Bashir',
            'An Inconvenient Truth',
            'Catfish',
            'Exit Through the Gift Shop',
            'Man on Wire',
            'Waste Land',
            '20 Feet from Stardom',
            'Searching for Sugar Man',
            'The Act of Killing',
            'Jiro Dreams of Sushi',
            'Blackfish',
            'Cave of Forgotten Dreams',
            'Won’t You Be My Neighbor?',
            'The Fog of War',
            'March of the Penguins',
            'The Cove',
            'Dear Zachary: A Letter to a Son About His Father',
            'The Queen of Versailles',
            'Bowling for Columbine',
            'The Corporation',
            'Sicko',
            'Grizzly Man',
            'The September Issue',
            'I Am Not Your Negro'
        ],
        fantasia: [
            'Harry Potter e a Pedra Filosofal',
            'Harry Potter e a Câmara Secreta',
            'Harry Potter e o Prisioneiro de Azkaban',
            'Harry Potter e o Cálice de Fogo',
            'Harry Potter e a Ordem da Fênix',
            'Harry Potter e o Enigma do Príncipe',
            'Harry Potter e as Relíquias da Morte: Parte 1',
            'Harry Potter e as Relíquias da Morte: Parte 2',
            'O Senhor dos Anéis: A Sociedade do Anel',
            'O Senhor dos Anéis: As Duas Torres',
            'O Senhor dos Anéis: O Retorno do Rei',
            'A Saga Crepúsculo: Lua Nova',
            'A Saga Crepúsculo: Eclipse',
            'A Saga Crepúsculo: Amanhecer – Parte 1',
            'A Saga Crepúsculo: Amanhecer – Parte 2',
            'O Hobbit: Uma Jornada Inesperada',
            'O Hobbit: A Desolação de Smaug',
            'O Hobbit: A Batalha dos Cinco Exércitos',
            'As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa',
            'As Crônicas de Nárnia: Príncipe Caspian',
            'As Crônicas de Nárnia: A Viagem do Peregrino da Alvorada',
            'Percy Jackson e o Ladrão de Raios',
            'Percy Jackson e o Mar de Monstros',
            'Percy Jackson e o Mar de Monstros',
            'Divertida Mente',
            'A Origem',
            'O Estranho Mundo de Jack',
            'Coraline e o Mundo Secreto',
            'O Fabuloso Destino de Amélie Poulain',
            'Edward Mãos de Tesoura',
            'O Labirinto do Fauno',
            'De Volta para o Futuro',
            'Labirinto - A Magia do Tempo',
            'Querido John'
        ],
        musical: [
            'O Rei Leão',
            'Mamma Mia!',
            'A Noviça Rebelde',
            'La La Land: Cantando Estações',
            'Os Miseráveis',
            'Frozen: Uma Aventura Congelante',
            'A Bela e a Fera',
            'Chicago',
            'O Fantasma da Ópera',
            'Moana: Um Mar de Aventuras',
            'Nasce uma Estrela',
            'Mary Poppins',
            'Sweeney Todd: O Barbeiro Demoníaco da Rua Fleet',
            'Rent',
            'Dreamgirls',
            'Hairspray: Em Busca da Fama',
            'A Pequena Loja dos Horrores',
            'Sinfonia de Paris',
            'Cantando na Chuva',
            'Les Girls',
            'Nós e o Fantasma',
            'Piratas do Caribe: No Fim do Mundo',
            'Em Busca do Vale Encantado',
            'Os Batutinhas',
            'Anastasia',
            'Coco',
            'O Pequeno Stuart Little',
            'Pinóquio',
            'A Pequena Sereia',
            'Shrek',
            'Mulan',
            'Os Incríveis',
            'A Nova Onda do Imperador',
            'O Galinho Chicken Little',
            'O Bicho Vai Pegar'
        ]
    };

    const imagensDosFilmes = {
        'Simplesmente Acontece': 'https://br.web.img3.acsta.net/pictures/14/12/11/15/29/051042.jpg',
    };

    const filmesDoTipoSelecionado = filmes[tipoFilme];
    const filmeAleatorio = filmesDoTipoSelecionado[Math.floor(Math.random() * filmesDoTipoSelecionado.length)];

    const imagemDoFilme = imagensDosFilmes[filmeAleatorio];

    const resultadoDiv = document.getElementById('resultado');
    resultadoDiv.innerHTML = `
        <h2>Que tal assistir a: <strong>${filmeAleatorio}</strong>?</h2>
        <img src="${imagemDoFilme}" alt="${filmeAleatorio}"> <!-- Exibe a imagem do filme -->
    `;
});
